## Project information
site_name: AnkiDojo
site_url: https://mathewthe2.github.io/AnkiDojo/
site_description: AnkiDojo is an easy-to-use and fully-featured Japanese toolkit for Anki.

# Copyright
copyright: AnkiDojo

## Social Media
extra:
  social:
    - icon: fontawesome/solid/house
      link: https://mathewthe2.github.io/AnkiDojo/
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/MathewChan10
    - icon: fontawesome/brands/discord
      link: https://discord.gg/wDePbmHxE2
    - icon: fontawesome/brands/github-alt
      link: https://github.com/mathewthe2/AnkiDojo
    - icon: fontawesome/solid/envelope
      link: mailto:mchan6466@gmail.com


## Page tree
nav:
    - Home: index.md
    - Getting Started: welcome.md


# Repository
repo_name: AnkiDojo
repo_url: https://github.com/mathewthe2/AnkiDojo
edit_uri: ''  #disables edit but

## Configuration
theme:
  name: material
  language: en
  palette:

  # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
      primary: pink
      accent: blue

  #   # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
      primary: pink
      accent: lime
  font:
    text: Roboto
    code: Roboto Mono

## Plugins
plugins:
  - search

## Extensions
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
